name: create_release

on:
  workflow_dispatch:
    inputs:
      skipTests:
        type: choice
        description: 'Skip Tests'
        options: ['true', 'false']
        default: 'false'
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'deploy/**'
      - '.github/**'
      - 'README.*'
      - '.devcontainer/**'
      - '.vscode/**'

jobs:
  create_release:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "geneie-variant-services"
      TAG_LATEST: latest
      TAG_SHA: ${{ github.sha }}
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Unit Tests
        run: ./run-unit-tests.sh
        if: github.event.inputs.skipTests != 'true'

      - name: Generate version number
        id: tag_version
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          
      - name: Build Docker Image
        env:
          VERSION: ${{ steps.tag_version.outputs.tag }}
        run: |
          echo "Building version: $VERSION"
          docker build --build-arg VERSION=$VERSION -t $IMAGE_NAME .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push your-dockerhub-username/your-image-name:${{ env.new_version }}
          
      - name: Create github release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.tag }}
          generateReleaseNotes: true
          allowUpdates: true