name: pull_request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - README.md
      - LICENSE

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Unit Tests
        run: ./run-unit-tests.sh